name:                daily-reps
version:             0.1.0.0
github:              "qxjit/dailyReps"
license:             BSD3
author:              "David Vollbracht"
maintainer:          "david.vollbracht@gmail.com"
copyright:           "2020 David Vollbracht"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/daily-reps#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- free

library:
  source-dirs: src

